---
version: '3'
services:
  pet_demo:
    build: .
    image: pet-demo:v1
    container_name: pet-demo
    ports:
      - 5000:5000
    environment:
      DATABASE_URI: "postgres://admin:s3cr3t@postgres:5432/postgres"
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - overlay

  # docker run -d --name postgres -p 5432:5432 -v pg_data:/var/lib/postgresql/data postgres:alpine
  postgres:
    image: postgres:alpine
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: s3cr3t
    networks:
      - overlay

volumes:
  pg_data:

networks:
  overlay:
